### PR TITLE
Add cfgenv - config from env.list

### PR DESCRIPTION
**Pull request by gclitheroe**

### CODE REVIEW

**Comment by junghao** [comment]
This func won't override the existing env var. I think it's ok when apps run in a container. 
But will this cause confusing when apps run in a normal OS or command line?

**Comment by gclitheroe** [comment]
What sort of confusion do you imagine?  Do you have an example?

**Comment by junghao** [comment]
Sorry I misunderstood how our cfg package used to work - this works the same way as before and I never have such confusion. So please ignore my comment.

**Comment by junghao** [comment]
I think this is good.

**Pull request merged**
